record:
  record_id: "035$a"
  record_leader: "008"
  language_code: "041$a"
  location_code: "043$a"
  note_title: "245$a"
  date_created: "260$c"
  date_created_approx: "264$c"
  physical_extent: "300$a"
  physical_details: "300$b"
  note_general: "500$a"
  note_summary: "520$a"
  series_title: "830$a"
  series_volume: "830$v"
subject:
  subject_name: ["100$a", "110$a", "600$a", "610$a"]
  subject_dates: ["100$d", "600$d"]
  subject_type: ["100$a", "100$d", "100$e", "110$a", "110$e", "600$a", "600$d", "610$a"]
image:
  image_id: "856$u"
  note_url: "856$u"
  note_public: "856$z"
  record_id: "record.record_id"
record_subject:
  record_id: "record.record_id"
  subject_name: "subject.subject_id"
image_topic:
image_location:

"100$a" : "subject_person_name_main"
"100$d" : "subject_person_dates_main"
"100$e" : "subject_person_relation_main"
"110$a" : "subject_company_name_main"
"110$e" : "subject_company_relation_main"
"600$a" : "subject_person_name_other"
"600$d" : "subject_person_dates_other"
"610$a" : "subject_company_name_other"
"650$a" : "image_topical_term"
"650$z" : "image_location_division"
"651$a" : "image_location_name"
