- "035$a" : "control_id"
- "041$a" : "language_code"
- "043$a" : "location_code"
- "100$a" : "subject_main_name"
- "100$d" : "subject_main_dates"
- "100$e" : "subject_main_relation"
- "110$a" : "subject_main_company_name"
- "110$e" : "subject_main_company_relation"
- "245$a" : "note_title"
- "260$c" : "date_created"
- "264$c" : "date_created_approx"
- "300$a" : "physical_extent"
- "300$b" : "physical_details"
- "500$a" : "note_general"
- "520$a" : "note_summary"
- "600$a" : "subject_person_name"
- "600$d" : "subject_person_dates"
- "610$a" : "subject_company_name"
- "650$a" : "note_topical_term"
- "650$z" : "location_division"
- "651$a" : "location_name"
- "830$a" : "series_title"
- "830$v" : "series_volume"
- "856$u" : "note_url"
- "856$z" : "note_public"
